/* Generated by Yosys 0.64+26 (git sha1 a54bca549, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* top =  1  *)
(* src = "counter.v:1.1-12.10" *)
module counter_4bit(clk, reset, count);
  (* src = "counter.v:2.8-2.11" *)
  input clk;
  wire clk;
  (* src = "counter.v:3.8-3.13" *)
  input reset;
  wire reset;
  (* src = "counter.v:4.19-4.24" *)
  output [3:0] count;
  reg [3:0] count;
  wire _00_;
  wire _01_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:9.11-9.20|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [31:0] _02_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:9.11-9.20|/apps/vlsi/tools/yosys/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "4" *)
  wire [31:0] _03_;
  INVX1 _04_ (
    .A(count[0]),
    .Y(_02_[0])
  );
  NAND2X1 _05_ (
    .A(count[1]),
    .B(count[0]),
    .Y(_00_)
  );
  NAND3X1 _06_ (
    .A(count[1]),
    .B(count[0]),
    .C(count[2]),
    .Y(_01_)
  );
  XNOR2X1 _07_ (
    .A(count[3]),
    .B(_01_),
    .Y(_03_[3])
  );
  XNOR2X1 _08_ (
    .A(count[2]),
    .B(_00_),
    .Y(_03_[2])
  );
  XOR2X1 _09_ (
    .A(count[1]),
    .B(count[0]),
    .Y(_03_[1])
  );
  (* src = "counter.v:5.2-11.4" *)
  always @(posedge clk, posedge reset)
    if (reset) count[0] <= 1'h0;
    else count[0] <= _02_[0];
  (* src = "counter.v:5.2-11.4" *)
  always @(posedge clk, posedge reset)
    if (reset) count[1] <= 1'h0;
    else count[1] <= _03_[1];
  (* src = "counter.v:5.2-11.4" *)
  always @(posedge clk, posedge reset)
    if (reset) count[2] <= 1'h0;
    else count[2] <= _03_[2];
  (* src = "counter.v:5.2-11.4" *)
  always @(posedge clk, posedge reset)
    if (reset) count[3] <= 1'h0;
    else count[3] <= _03_[3];
  assign { _03_[31:5], _03_[0] } = { 27'h0000000, _02_[0] };
  assign _02_[31:1] = { 28'h0000000, count[3:1] };
endmodule
